### ISSUE TITLE
Error Resetting Private Key

### ISSUE THREAD

**Issue by daconrad0** [postlund/dlink_hnap#9]
I have an S-161 Water Sensor and am getting an error on setup.

I am running latest version of HA

![image](https://user-images.githubusercontent.com/48894833/88847191-b1786f80-d1b4-11ea-839b-a6a17fea8fbc.png)

![image](https://user-images.githubusercontent.com/48894833/88847266-c7863000-d1b4-11ea-9390-859af1d5111c.png)

I have attached the configuration as well.  This is the file under binary sensors.

![image](https://user-images.githubusercontent.com/48894833/88847390-f8fefb80-d1b4-11ea-9fc1-fe8467519a5d.png)

This is also in the log file

Log Details (ERROR)
Logger: custom_components.dlink_hnap.binary_sensor
Source: custom_components/dlink_hnap/dlink.py:126
Integration: dlink_hnap (documentation, issues)
First occurred: 3:58:23 PM (63 occurrences)
Last logged: 4:03:35 PM

failed to update water sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.37', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/dlink.py", line 116, in call
    result = await self.soap().call(method, **kwargs)
  File "/config/custom_components/dlink_hnap/dlink.py", line 253, in call
    resp = await self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.37:80 ssl:None [Connect call failed ('192.168.1.37', 80)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/binary_sensor.py", line 142, in async_update
    water_detected = await self._sensor.water_detected()
  File "/config/custom_components/dlink_hnap/dlink.py", line 206, in water_detected
    await self._cache_soap_actions()
  File "/config/custom_components/dlink_hnap/dlink.py", line 192, in _cache_soap_actions
    resp = await self.client.soap_actions(self.module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 106, in soap_actions
    return await self.call("GetModuleSOAPActions", ModuleID=module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 112, in call
    await self.login()
  File "/config/custom_components/dlink_hnap/dlink.py", line 57, in login
    resp = await self.call(
  File "/config/custom_components/dlink_hnap/dlink.py", line 120, in call
    self._bad_response()
  File "/config/custom_components/dlink_hnap/dlink.py", line 126, in _bad_response
    raise Exception("got error response from device")
Exception: got error response from device
Home Assistant has started!

**Comment by postlund** [comment]
If you open up a web browser and navigate to the IP of your sensor, does that work? Seems to be a network problem.

**Comment by ghitchen** [comment]
I had a similar error (many, many times) using DCH-S150 motion sensors. Reading the comment above I connected to each one using a browser to check that the connection was okay (it was) and since then I haven't had the errors. It might be a coincidence but it was happening all the time before and now it hasn't happened for a few hours. I will keep an eye on the logs and let you know if it returns.

**Comment by daconrad0** [comment]
Resolved by deleting sensor and re-adding.
